# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_cpp_utils', [dirname(__file__)])
        except ImportError:
            import _cpp_utils
            return _cpp_utils
        if fp is not None:
            try:
                _mod = imp.load_module('_cpp_utils', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _cpp_utils = swig_import_helper()
    del swig_import_helper
else:
    import _cpp_utils
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _cpp_utils.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _cpp_utils.SwigPyIterator_value(self)
    def incr(self, n=1): return _cpp_utils.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _cpp_utils.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _cpp_utils.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _cpp_utils.SwigPyIterator_equal(self, *args)
    def copy(self): return _cpp_utils.SwigPyIterator_copy(self)
    def next(self): return _cpp_utils.SwigPyIterator_next(self)
    def __next__(self): return _cpp_utils.SwigPyIterator___next__(self)
    def previous(self): return _cpp_utils.SwigPyIterator_previous(self)
    def advance(self, *args): return _cpp_utils.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _cpp_utils.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _cpp_utils.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _cpp_utils.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _cpp_utils.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _cpp_utils.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _cpp_utils.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _cpp_utils.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _cpp_utils.IntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _cpp_utils.IntVector___nonzero__(self)
    def __bool__(self): return _cpp_utils.IntVector___bool__(self)
    def __len__(self): return _cpp_utils.IntVector___len__(self)
    def pop(self): return _cpp_utils.IntVector_pop(self)
    def __getslice__(self, *args): return _cpp_utils.IntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _cpp_utils.IntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _cpp_utils.IntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _cpp_utils.IntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _cpp_utils.IntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _cpp_utils.IntVector___setitem__(self, *args)
    def append(self, *args): return _cpp_utils.IntVector_append(self, *args)
    def empty(self): return _cpp_utils.IntVector_empty(self)
    def size(self): return _cpp_utils.IntVector_size(self)
    def clear(self): return _cpp_utils.IntVector_clear(self)
    def swap(self, *args): return _cpp_utils.IntVector_swap(self, *args)
    def get_allocator(self): return _cpp_utils.IntVector_get_allocator(self)
    def begin(self): return _cpp_utils.IntVector_begin(self)
    def end(self): return _cpp_utils.IntVector_end(self)
    def rbegin(self): return _cpp_utils.IntVector_rbegin(self)
    def rend(self): return _cpp_utils.IntVector_rend(self)
    def pop_back(self): return _cpp_utils.IntVector_pop_back(self)
    def erase(self, *args): return _cpp_utils.IntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _cpp_utils.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _cpp_utils.IntVector_push_back(self, *args)
    def front(self): return _cpp_utils.IntVector_front(self)
    def back(self): return _cpp_utils.IntVector_back(self)
    def assign(self, *args): return _cpp_utils.IntVector_assign(self, *args)
    def resize(self, *args): return _cpp_utils.IntVector_resize(self, *args)
    def insert(self, *args): return _cpp_utils.IntVector_insert(self, *args)
    def reserve(self, *args): return _cpp_utils.IntVector_reserve(self, *args)
    def capacity(self): return _cpp_utils.IntVector_capacity(self)
    __swig_destroy__ = _cpp_utils.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _cpp_utils.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _cpp_utils.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _cpp_utils.DoubleVector___nonzero__(self)
    def __bool__(self): return _cpp_utils.DoubleVector___bool__(self)
    def __len__(self): return _cpp_utils.DoubleVector___len__(self)
    def pop(self): return _cpp_utils.DoubleVector_pop(self)
    def __getslice__(self, *args): return _cpp_utils.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _cpp_utils.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _cpp_utils.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _cpp_utils.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _cpp_utils.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _cpp_utils.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _cpp_utils.DoubleVector_append(self, *args)
    def empty(self): return _cpp_utils.DoubleVector_empty(self)
    def size(self): return _cpp_utils.DoubleVector_size(self)
    def clear(self): return _cpp_utils.DoubleVector_clear(self)
    def swap(self, *args): return _cpp_utils.DoubleVector_swap(self, *args)
    def get_allocator(self): return _cpp_utils.DoubleVector_get_allocator(self)
    def begin(self): return _cpp_utils.DoubleVector_begin(self)
    def end(self): return _cpp_utils.DoubleVector_end(self)
    def rbegin(self): return _cpp_utils.DoubleVector_rbegin(self)
    def rend(self): return _cpp_utils.DoubleVector_rend(self)
    def pop_back(self): return _cpp_utils.DoubleVector_pop_back(self)
    def erase(self, *args): return _cpp_utils.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _cpp_utils.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _cpp_utils.DoubleVector_push_back(self, *args)
    def front(self): return _cpp_utils.DoubleVector_front(self)
    def back(self): return _cpp_utils.DoubleVector_back(self)
    def assign(self, *args): return _cpp_utils.DoubleVector_assign(self, *args)
    def resize(self, *args): return _cpp_utils.DoubleVector_resize(self, *args)
    def insert(self, *args): return _cpp_utils.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _cpp_utils.DoubleVector_reserve(self, *args)
    def capacity(self): return _cpp_utils.DoubleVector_capacity(self)
    __swig_destroy__ = _cpp_utils.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _cpp_utils.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class IntVector2D(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector2D, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector2D, name)
    __repr__ = _swig_repr
    def iterator(self): return _cpp_utils.IntVector2D_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _cpp_utils.IntVector2D___nonzero__(self)
    def __bool__(self): return _cpp_utils.IntVector2D___bool__(self)
    def __len__(self): return _cpp_utils.IntVector2D___len__(self)
    def pop(self): return _cpp_utils.IntVector2D_pop(self)
    def __getslice__(self, *args): return _cpp_utils.IntVector2D___getslice__(self, *args)
    def __setslice__(self, *args): return _cpp_utils.IntVector2D___setslice__(self, *args)
    def __delslice__(self, *args): return _cpp_utils.IntVector2D___delslice__(self, *args)
    def __delitem__(self, *args): return _cpp_utils.IntVector2D___delitem__(self, *args)
    def __getitem__(self, *args): return _cpp_utils.IntVector2D___getitem__(self, *args)
    def __setitem__(self, *args): return _cpp_utils.IntVector2D___setitem__(self, *args)
    def append(self, *args): return _cpp_utils.IntVector2D_append(self, *args)
    def empty(self): return _cpp_utils.IntVector2D_empty(self)
    def size(self): return _cpp_utils.IntVector2D_size(self)
    def clear(self): return _cpp_utils.IntVector2D_clear(self)
    def swap(self, *args): return _cpp_utils.IntVector2D_swap(self, *args)
    def get_allocator(self): return _cpp_utils.IntVector2D_get_allocator(self)
    def begin(self): return _cpp_utils.IntVector2D_begin(self)
    def end(self): return _cpp_utils.IntVector2D_end(self)
    def rbegin(self): return _cpp_utils.IntVector2D_rbegin(self)
    def rend(self): return _cpp_utils.IntVector2D_rend(self)
    def pop_back(self): return _cpp_utils.IntVector2D_pop_back(self)
    def erase(self, *args): return _cpp_utils.IntVector2D_erase(self, *args)
    def __init__(self, *args): 
        this = _cpp_utils.new_IntVector2D(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _cpp_utils.IntVector2D_push_back(self, *args)
    def front(self): return _cpp_utils.IntVector2D_front(self)
    def back(self): return _cpp_utils.IntVector2D_back(self)
    def assign(self, *args): return _cpp_utils.IntVector2D_assign(self, *args)
    def resize(self, *args): return _cpp_utils.IntVector2D_resize(self, *args)
    def insert(self, *args): return _cpp_utils.IntVector2D_insert(self, *args)
    def reserve(self, *args): return _cpp_utils.IntVector2D_reserve(self, *args)
    def capacity(self): return _cpp_utils.IntVector2D_capacity(self)
    __swig_destroy__ = _cpp_utils.delete_IntVector2D
    __del__ = lambda self : None;
IntVector2D_swigregister = _cpp_utils.IntVector2D_swigregister
IntVector2D_swigregister(IntVector2D)

class DoubleVector2D(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector2D, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector2D, name)
    __repr__ = _swig_repr
    def iterator(self): return _cpp_utils.DoubleVector2D_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _cpp_utils.DoubleVector2D___nonzero__(self)
    def __bool__(self): return _cpp_utils.DoubleVector2D___bool__(self)
    def __len__(self): return _cpp_utils.DoubleVector2D___len__(self)
    def pop(self): return _cpp_utils.DoubleVector2D_pop(self)
    def __getslice__(self, *args): return _cpp_utils.DoubleVector2D___getslice__(self, *args)
    def __setslice__(self, *args): return _cpp_utils.DoubleVector2D___setslice__(self, *args)
    def __delslice__(self, *args): return _cpp_utils.DoubleVector2D___delslice__(self, *args)
    def __delitem__(self, *args): return _cpp_utils.DoubleVector2D___delitem__(self, *args)
    def __getitem__(self, *args): return _cpp_utils.DoubleVector2D___getitem__(self, *args)
    def __setitem__(self, *args): return _cpp_utils.DoubleVector2D___setitem__(self, *args)
    def append(self, *args): return _cpp_utils.DoubleVector2D_append(self, *args)
    def empty(self): return _cpp_utils.DoubleVector2D_empty(self)
    def size(self): return _cpp_utils.DoubleVector2D_size(self)
    def clear(self): return _cpp_utils.DoubleVector2D_clear(self)
    def swap(self, *args): return _cpp_utils.DoubleVector2D_swap(self, *args)
    def get_allocator(self): return _cpp_utils.DoubleVector2D_get_allocator(self)
    def begin(self): return _cpp_utils.DoubleVector2D_begin(self)
    def end(self): return _cpp_utils.DoubleVector2D_end(self)
    def rbegin(self): return _cpp_utils.DoubleVector2D_rbegin(self)
    def rend(self): return _cpp_utils.DoubleVector2D_rend(self)
    def pop_back(self): return _cpp_utils.DoubleVector2D_pop_back(self)
    def erase(self, *args): return _cpp_utils.DoubleVector2D_erase(self, *args)
    def __init__(self, *args): 
        this = _cpp_utils.new_DoubleVector2D(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _cpp_utils.DoubleVector2D_push_back(self, *args)
    def front(self): return _cpp_utils.DoubleVector2D_front(self)
    def back(self): return _cpp_utils.DoubleVector2D_back(self)
    def assign(self, *args): return _cpp_utils.DoubleVector2D_assign(self, *args)
    def resize(self, *args): return _cpp_utils.DoubleVector2D_resize(self, *args)
    def insert(self, *args): return _cpp_utils.DoubleVector2D_insert(self, *args)
    def reserve(self, *args): return _cpp_utils.DoubleVector2D_reserve(self, *args)
    def capacity(self): return _cpp_utils.DoubleVector2D_capacity(self)
    __swig_destroy__ = _cpp_utils.delete_DoubleVector2D
    __del__ = lambda self : None;
DoubleVector2D_swigregister = _cpp_utils.DoubleVector2D_swigregister
DoubleVector2D_swigregister(DoubleVector2D)

class DoubleVector3D(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector3D, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector3D, name)
    __repr__ = _swig_repr
    def iterator(self): return _cpp_utils.DoubleVector3D_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _cpp_utils.DoubleVector3D___nonzero__(self)
    def __bool__(self): return _cpp_utils.DoubleVector3D___bool__(self)
    def __len__(self): return _cpp_utils.DoubleVector3D___len__(self)
    def pop(self): return _cpp_utils.DoubleVector3D_pop(self)
    def __getslice__(self, *args): return _cpp_utils.DoubleVector3D___getslice__(self, *args)
    def __setslice__(self, *args): return _cpp_utils.DoubleVector3D___setslice__(self, *args)
    def __delslice__(self, *args): return _cpp_utils.DoubleVector3D___delslice__(self, *args)
    def __delitem__(self, *args): return _cpp_utils.DoubleVector3D___delitem__(self, *args)
    def __getitem__(self, *args): return _cpp_utils.DoubleVector3D___getitem__(self, *args)
    def __setitem__(self, *args): return _cpp_utils.DoubleVector3D___setitem__(self, *args)
    def append(self, *args): return _cpp_utils.DoubleVector3D_append(self, *args)
    def empty(self): return _cpp_utils.DoubleVector3D_empty(self)
    def size(self): return _cpp_utils.DoubleVector3D_size(self)
    def clear(self): return _cpp_utils.DoubleVector3D_clear(self)
    def swap(self, *args): return _cpp_utils.DoubleVector3D_swap(self, *args)
    def get_allocator(self): return _cpp_utils.DoubleVector3D_get_allocator(self)
    def begin(self): return _cpp_utils.DoubleVector3D_begin(self)
    def end(self): return _cpp_utils.DoubleVector3D_end(self)
    def rbegin(self): return _cpp_utils.DoubleVector3D_rbegin(self)
    def rend(self): return _cpp_utils.DoubleVector3D_rend(self)
    def pop_back(self): return _cpp_utils.DoubleVector3D_pop_back(self)
    def erase(self, *args): return _cpp_utils.DoubleVector3D_erase(self, *args)
    def __init__(self, *args): 
        this = _cpp_utils.new_DoubleVector3D(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _cpp_utils.DoubleVector3D_push_back(self, *args)
    def front(self): return _cpp_utils.DoubleVector3D_front(self)
    def back(self): return _cpp_utils.DoubleVector3D_back(self)
    def assign(self, *args): return _cpp_utils.DoubleVector3D_assign(self, *args)
    def resize(self, *args): return _cpp_utils.DoubleVector3D_resize(self, *args)
    def insert(self, *args): return _cpp_utils.DoubleVector3D_insert(self, *args)
    def reserve(self, *args): return _cpp_utils.DoubleVector3D_reserve(self, *args)
    def capacity(self): return _cpp_utils.DoubleVector3D_capacity(self)
    __swig_destroy__ = _cpp_utils.delete_DoubleVector3D
    __del__ = lambda self : None;
DoubleVector3D_swigregister = _cpp_utils.DoubleVector3D_swigregister
DoubleVector3D_swigregister(DoubleVector3D)


def delete_duplicates_int(*args):
  return _cpp_utils.delete_duplicates_int(*args)
delete_duplicates_int = _cpp_utils.delete_duplicates_int

def delete_duplicates_dbl(*args):
  return _cpp_utils.delete_duplicates_dbl(*args)
delete_duplicates_dbl = _cpp_utils.delete_duplicates_dbl

def test_rows(*args):
  return _cpp_utils.test_rows(*args)
test_rows = _cpp_utils.test_rows

def replace_with_idx(*args):
  return _cpp_utils.replace_with_idx(*args)
replace_with_idx = _cpp_utils.replace_with_idx

def replace_with_idx_int(*args):
  return _cpp_utils.replace_with_idx_int(*args)
replace_with_idx_int = _cpp_utils.replace_with_idx_int
# This file is compatible with both classic and new-style classes.


